### ISSUE TITLE
The process for adding a member is ad hoc.

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#26]
While there is a statute that requires two thirds agreement to admit a new member, 
there is no description of how a member of the community is to be considered for 
membership.

This means each potential member is considered on an ad-hoc basis. 

There should be a standard process for adding members.

**Comment by sliptonic** [comment]
There is a process for adding members now.  It is by posting a poll which runs until it either passes or is defeated.
What is not standardized is how to _evaluate_ candidates.

My opinion is that a standard process isn't needed because each candidate's history is unique and openly available.   We can read their forum posts, study code if they wrote it, look at how they took feedback,  see how long they've been active in the community and in which areas.

**Comment by donovaly** [comment]
I don't see that we need to standardize here.
The FPA is a group of people who want to work together to achieve the goals described in the statue.
In order to do so we must know each other well enough to have a base for a vote decision. Since we need to work together knowing each other is important. (There will always be kind of work/interest groups).

So either we know the proposed member well enough to vote about him/her or we meet him/her. I mean in the later work together, we will meet anyway and since we are scattered over the planet, these will in most cases be virtual meetings.
